FROM rust:1.56
WORKDIR /usr/src/myapp
COPY . .
RUN cargo install --locked trunk
RUN cargo install wasm-bindgen-cli
RUN rustup target add wasm32-unknown-unknown
CMD trunk build --release
CMD trunk serve